"""empty message

Revision ID: 8e5da715cb6d
Revises: 955117a70d3d
Create Date: 2024-02-29 19:10:59.137073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5da715cb6d'
down_revision = '955117a70d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_characters_characters_id_key', type_='unique')
        batch_op.drop_constraint('favorite_characters_user_id_key', type_='unique')

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_planets_planets_id_key', type_='unique')
        batch_op.drop_constraint('favorite_planets_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorite_planets_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('favorite_planets_planets_id_key', ['planets_id'])

    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorite_characters_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('favorite_characters_characters_id_key', ['characters_id'])

    # ### end Alembic commands ###
